# version 450
//* resources:

#extension GL_EXT_shader_image_load_formatted : require

layout(push_constant) uniform Push {
    bool vert;
    float near;
    float far;
};

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding=0) readonly uniform image2D Ii; // color image
layout(binding=1) uniform image2D Ci; // control image
layout(binding=2) uniform image2D Bluri; // blurred image
layout(binding=3) uniform image2D Bi; // bleed image
layout(binding=4) uniform sampler2D Si; // Surface image

layout(binding=5) uniform image2D Wi;

vec4 I(ivec2 p){
    return imageLoad(Ii, p);
}

vec4 C(ivec2 p){
    return imageLoad(Ci, p);
}

vec4 Blur(ivec2 p){
    return imageLoad(Bluri, p);
}

vec4 B(ivec2 p){
    return imageLoad(Bi, p);
}

vec4 S(ivec2 p){
    return texelFetch(Si, p, 0);
}

// Red - Controls paper distortion.
// Green - Controls paper granulation.
// Blue - Controls edge darkening and color bleeding.
// Alpha - Controls pigment turbulence and pigment fading.

void main(){
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    //* texelFetch(Zi, texelCoord, 0).r
    
    //bleedBlur(p);
    vec4 paperTexture = clamp(texelFetch(Si, p, 0), vec4(0),vec4(1));
    //imageStore(Wi, p, B(p) * paperTexture.x);
    float ctrl = C(p).b;

    vec4 B = B(p);
    vec4 I = I(p);
    vec4 Ib = Blur(p);
    vec4 Icb = ctrl*(B - I) + I;
   
    vec4 diff = Ib-I;
    float m = max(diff.r, max(diff.g, diff.b));
    float exp = 1+ctrl*m;
    vec3 Ied = clamp(vec3(pow(Icb.r, exp), pow(Icb.g, exp), pow(Icb.b, exp)), vec3(0), vec3(1));


    //imageStore(Wi, p, B(p) * paperTexture.x);
    vec3 Cp = vec3(146.0/255.0, 128.0/255.0, 127.0/255.0)*paperTexture.x;
    vec3 final = Ied * paperTexture.x;
    final = vec3(min(Cp.x, final.x),min(Cp.y, final.y),min(Cp.z, final.z));
    imageStore(Wi, p, vec4(final, 1.0));

}