# version 450
//* resources:

#extension GL_EXT_shader_image_load_formatted : require

layout(push_constant) uniform Push {
    bool vert;
    float near;
    float far;
};

layout(local_size_x = 8, local_size_y = 8) in;
layout(binding=0) readonly uniform image2D Ii; // color image
layout(binding=1) uniform image2D Ci; // control image
layout(binding=2) uniform image2D Bluri; // blurred image
layout(binding=3) uniform image2D Bi; // bleed image
layout(binding=4) uniform sampler2D Si; // Surface image

layout(binding=5) uniform image2D Wi;

vec4 I(ivec2 p){
    return imageLoad(Ii, p);
}

vec4 C(ivec2 p){
    return imageLoad(Ci, p);
}

vec4 Blur(ivec2 p){
    return imageLoad(Bluri, p);
}

vec4 B(ivec2 p){
    return imageLoad(Bi, p);
}

vec4 S(ivec2 p){
    return texelFetch(Si, p, 0);
}

// Red - Controls paper distortion.
// Green - Controls paper granulation.
// Blue - Controls edge darkening and color bleeding.
// Alpha - Controls pigment turbulence and pigment fading.

void main(){
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);
    //* texelFetch(Zi, texelCoord, 0).r
    
    //bleedBlur(p);
    vec4 paperTexture = texelFetch(Si, p, 0);
    //imageStore(Wi, p, B(p) * paperTexture.x);
    float ctrl = 1.0;//C(p).b;

    vec4 B = B(p);
    vec4 I = I(p);
    vec4 Ib = Blur(p);
    vec4 Icb = ctrl*(B - I) + I;
   
    vec4 diff = Ib-I;
    float m = max(diff.r, max(diff.g, diff.b));
    float exp = 1+ctrl*m;
    vec4 Ied = vec4(pow(Icb.r, exp), pow(Icb.g, exp), pow(Icb.b, exp), 1.0);


    //imageStore(Wi, p, B(p) * paperTexture.x);
    imageStore(Wi, p, Ied);


}